### PR TITLE
Add end_time, update API version to 2.7

### PR DESCRIPTION
**Pull request by SToto98**

### CODE REVIEW

**Comment by tobilg** [comment]
Thanks for the PR. May I ask why you updated the Graph API version? I'm aware that there's v2.7, but I set this explicitly. 

Furthermore, you can overwrite the `version`, see https://github.com/tobilg/facebook-events-by-location-core#parameters

**Comment by SToto98** [comment]
Hi, I didn't see any inconsistency with your code and version 2.7 so why not using the latest one by default ? but maybe I missed something ?

**Comment by tobilg** [comment]
Please also add the `endTime` field in the JSON schema, otherwise the tests will faild: https://github.com/tobilg/facebook-events-by-location-core/blob/master/schema/events-response.schema.json#L34

**Comment by SToto98** [comment]
ok, sorry I didn't see that. I'll add this in my next commit. 
I need some more infos from the Facebook API such as `owner` and `type` (and maybe one or two more), are you OK if I add them ?

**Comment by tobilg** [comment]
Concerning `owner`, I guess it will always be the `id` of the place... If you check this and it's not the case, you can add this as `ownerId` field. Regarding the `type`, you won't see `private` events, only `{ public, group, community }`

**Comment by SToto98** [comment]
For the `owner` I already checked this and some owners have public infos (like name, about, emails, etc.) which are accessibles. For the `type`, if my app (access_token) has been given the right to see them by someone, then private events can be viewed and I need to know when.

**Comment by tobilg** [comment]
I guess you see the public info of the place, not of individuals... Nevertheless, I'd only accept the `ownerId` as a single field, not a subobject.

**Comment by SToto98** [comment]
OK, so I've just added the missing `endTime` in the JSON schema. You can merge and I'll will continue my updates on my own branch, It'll be easier for me :) Thanks for your work, very useful !

**Comment by tobilg** [comment]
Can you please fix the indention, and the JSON schema for `emails`? It can also be `null` according to your code. Thanks

**Comment by SToto98** [comment]
Sure, done!

**Comment by tobilg** [comment]
Thanks, I'm merging now and will publish a new version to npm later

**Comment by tobilg** [comment]
Version `0.1.3` was just published.

**Comment by SToto98** [comment]
Thanks!

**Pull request merged**
